# Inherit from the e2e_mask_rcnn_R-101-FPN_2x.yaml
# Add Indicator component to the cfg
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 81
  FASTER_RCNN: True
  MASK_ON: True
  REFINE_ON: True
  REFINE_KEYPOINTS_ON: True
NUM_GPUS: 2 
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.005
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
REFINENET:
  HEAD: MRCNN_FCN   # default is HOURGLASS
  INDICATOR_TYPE: Mask # Indicator type, mask or keypoint
  REFINE_OUTPUT_TYPE: Mask   # Refine output type, mask or keypoint
  SPATIAL_SCALE: 0.125 # down-sampling scale for the indicator
  WEIGHT_LOSS_MASK: 1.0
  UP_SCALE: 2   # upscale factor for local indicator
  STRIDE: 1  # default 1, 16 only for hourglass 
  RESOLUTION: 56  # default 28
  LOCAL_MASK: True # Use local mask as indicator
  USE_GPU: True # Use gpu for fast feature abstract
  ROI_XFORM_SAMPLING_RATIO: 2
  ROI_XFORM_RESOLUTION: 28
  MRCNN_FCN:
    NUM_CONVS: 8  # default 4
    USE_DECONV: True # Use deconv to the head
HG:
  DIM_FEATS: 256  # dimension number of hourglass unit
  NUM_STACKS: 1   # number of stacked hourglass
#DATA_LOADER:
#    NUM_THREADS: 2 # default is 4
TRAIN:
  WEIGHTS: /data/data/models/R-50.pkl
  DATASETS: ('coco_2014_train', 'coco_2014_valminusminival')
  #DATASETS: ('coco_2014_minival', 'coco_2014_minival') # For debugging
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 2 
  BATCH_SIZE_PER_IM: 128 
  SNAPSHOT_ITERS: 5000
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level



MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  KEYPOINTS_ON: True
  REFINE_ON: True
  REFINE_KEYPOINTS_ON: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 90000
  STEPS: [0, 60000, 80000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: head_builder.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
KRCNN:
  ROI_KEYPOINTS_HEAD: keypoint_rcnn_heads.add_roi_pose_head_v1convX
  NUM_STACKED_CONVS: 8
  NUM_KEYPOINTS: 17
  USE_DECONV_OUTPUT: True
  CONV_INIT: MSRAFill
  CONV_HEAD_DIM: 512
  UP_SCALE: 2
  HEATMAP_SIZE: 56  # ROI_XFORM_RESOLUTION (14) * UP_SCALE (2) * USE_DECONV_OUTPUT (2)
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  KEYPOINT_CONFIDENCE: bbox
REFINENET:
  REFINENET:
  HEAD: KRCNN   # default is HOURGLASS
  INDICATOR_TYPE: Keypoint # Indicator type, mask or keypoint
  REFINE_OUTPUT_TYPE: Mask   # Refine output type, mask or keypoint
  UP_SCALE: 2   # upscale factor for local indicator
  RESOLUTION: 56  # default 28
  ROI_XFORM_SAMPLING_RATIO: 2
  ROI_XFORM_RESOLUTION: 28
  KRCNN:
    NUM_STACKED_CONVS: 8
    NUM_KEYPOINTS: 17
    USE_DECONV_OUTPUT: True
    CONV_INIT: MSRAFill
    CONV_HEAD_DIM: 512
    UP_SCALE: 2
    HEATMAP_SIZE: 128  # ROI_XFORM_RESOLUTION (14) * UP_SCALE (2) * USE_DECONV_OUTPUT (2)
    KEYPOINT_CONFIDENCE: bbox
TRAIN:
  WEIGHTS: /root/data/models/R-50.pkl
  # DATASETS: ('keypoints_coco_2014_train', 'keypoints_coco_2014_valminusminival')
  DATASETS: ('keypoints_coco_2014_minival',)
  SCALES: (640, 672, 704, 736, 768, 800)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 128
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  DATASETS: ('keypoints_coco_2014_minival',)
  SCALES: (800,)
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .

