MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  KEYPOINTS_ON: True
  REFINE_ON: True
  REFINE_KEYPOINTS_ON: True
NUM_GPUS: 4 
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 90000
  STEPS: [0, 60000, 80000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: head_builder.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
KRCNN:
  ROI_KEYPOINTS_HEAD: keypoint_rcnn_heads.add_roi_pose_head_v1convX
  NUM_STACKED_CONVS: 8
  NUM_KEYPOINTS: 17
  USE_DECONV_OUTPUT: True
  CONV_INIT: MSRAFill
  CONV_HEAD_DIM: 512
  UP_SCALE: 2
  HEATMAP_SIZE: 56  # ROI_XFORM_RESOLUTION (14) * UP_SCALE (2) * USE_DECONV_OUTPUT (2)
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  KEYPOINT_CONFIDENCE: bbox
REFINENET:
  HEAD: KRCNN   # default is HOURGLASS
  INDICATOR_TYPE: Keypoint # Indicator type, mask or keypoint
  REFINE_OUTPUT_TYPE: Mask   # Refine output type, mask or keypoint
  UP_SCALE: 2   # upscale factor for local indicator
  RESOLUTION: 112 # default 28
  ROI_XFORM_SAMPLING_RATIO: 2
  ROI_XFORM_RESOLUTION: 28
  KRCNN:
    NUM_STACKED_CONVS: 8
    NUM_KEYPOINTS: 17
    USE_DECONV_OUTPUT: True
    CONV_INIT: MSRAFill
    CONV_HEAD_DIM: 512
    UP_SCALE: 2
    HEATMAP_SIZE: 112 # ROI_XFORM_RESOLUTION (14) * UP_SCALE (2) * USE_DECONV_OUTPUT (2)
    KEYPOINT_CONFIDENCE: bbox
TRAIN:
  WEIGHTS: /root/data/models/R-50.pkl
  # DATASETS: ('keypoints_coco_2014_train', 'keypoints_coco_2014_valminusminival')
  DATASETS: ('keypoints_coco_2014_minival',)
  SCALES: (640, 672, 704, 736, 768, 800)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 128
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  DATASETS: ('keypoints_coco_2014_minival',)
  SCALES: (800,)
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .

